{% set version = '2.9-1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mboost
  version: {{ version|replace("-", "_") }}

source:
  fn: mboost_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/mboost_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mboost/mboost_{{ version }}.tar.gz
  sha256: 67ed26093fc2c1e57d7fac842a51a0de0162e448d4dab09c0054baee801f2a0a

build:
  merge_build_host: True  # [win]
  number: 1001
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-lattice
    - r-nnls
    - r-partykit >=1.2_1
    - r-quadprog
    - r-stabs >=0.5_0
    - r-survival
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix
    - r-lattice
    - r-nnls
    - r-partykit >=1.2_1
    - r-quadprog
    - r-stabs >=0.5_0
    - r-survival

test:
  commands:
    - $R -e "library('mboost')"           # [not win]
    - "\"%R%\" -e \"library('mboost')\""  # [win]

about:
  home: https://github.com/boost-R/mboost
  license: GPL-2
  summary: Functional gradient descent algorithm (boosting) for optimizing general risk functions
    utilizing component-wise (penalised) least squares estimates or regression trees
    as base-learners for fitting generalized linear, additive and interaction models
    to potentially high-dimensional data.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
