travis:
  secure:
    BINSTAR_TOKEN: Mk0N09FKFjBJnEZiclbtRGQfHymhY21DA4s8eKfZV6EolrzKKFLg7QhCEyFX6F1IQayPw6eOeGFjXV3LrIF/F12ZVWMrn6c/Wru1oaUnqjKqdIkZqQGLNWDGkjBO3YO3YK9+tTHktCNMC2hyeFdTYEM7rUgIGkldzMaG7SF9nS0heczQ6tq1NNevCHpGOhPPuGRRlWDsO1uqxaU0/VGflTF6n5XYlZ09+K3JAdHJ3Qyliap5bLafUvnJahLktf23WEXTagbPAOMLUaWbL1QB4NCdxAEq71OXRK8pSYYFwMwsuFYTch7DZYDhKiKlb+RZTHey8Qci62+LovikcCfNaU8CmorlYUERUHE6a0omcAmhInGvNHbYNbLz4AeSg3rfcqDmXxXKqnPutpEsTaX5yiMfq3VXNjpU3KSX+CQmB29KnrXYA49lCFNT2FVQPE6gCYzTbsGMniemII0CCPmAG1csZrbAxJAZvaGxDsCJZkEhuW9oEXa0PLy9dYHEnu0m9lnMbpeRu0sj2gBl/dO2J3pCNsMiCbqX1D+XOid4++2K4OdY3z5l/bbODJXoLoeN7DCxwj778OlUUV6aEEQeEJmED8VSUaxyF0KB3KPwx1IY6ruabgd0xIVrP91D4RrJI+hYwneU3C6BYF3I1GswEGtMyeeM53x7MvUBrLcbFDQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
