travis:
  secure:
    BINSTAR_TOKEN: e7kPU4+W7KrDH0OW38g3e7papJhaFp4xOmUU8uVitbO5LVo0uDMb2btOjg9Xuy27IMqVGRHyXrhZcE7tKiz6h0CdebfVMnrkceJO8Ssoxrza8KTS8/UbG5eZfa5Wz/u+ki8AaAmZoxe5FZBqYGAxXMmSQrJZ4OqNCYOKpvhZM+JkV7rzKVSo1B6PCMLZmzxYXAhGAqzfnM/VmaBoa239lykDxeyEnb/0IuF+co/40lyPOQPr8AV2J/jYXnX1KIRITafPh6KgRgWmntXLycWow3R50jlo+6VdALqpv7XrWaz+kb/ywGoF5+6QdltYdrFAcluZvopPYFl2qOpDrKI6aAEDaupIJFaGM1mcAYB8AU52PIiWf6Fa/3bcVqszi9kTjSw3CwHg+fv0vFXX67/J9b22j+0Eb7jCiqAuP68F0aApucTrv9NsShYGFA8cx3F64x6PC2T1e91Dn3e7HBqaC4abhOws2C2GZ1qIZ9j7bEfWtJtsyiP/UONp5p4eMJQcKQvwVNNWLGk/q3V/Z4Socu88zxcGwYIV0cKK4BDvxmtyVHGuUcaTSjlLYSE8d+Me0P0e9Y9Y55ENi4dA5YoqITJkpCOXbxB4GBA9Wq/BPDgVbHbMODJgbGi1WmV0VaKnQQTT9eLLl62WwBCVIhexxXY7NVJMcBY/ykCM2AklnEo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
